version: "3"

services:
    node:
        ports:
            - "8080:3000"
        networks:
            - webnet
        build:
            context: ./
            dockerfile: Dockerfile
networks:
    webnet: