version: "3"

services:
    sql:
        ports:
            - "1433:1433"
        networks:
            - sqlnet
        image: microsoft/mssql-server-linux
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
networks:
    sqlnet: